#!/usr/bin/env python3

from syntester.syntester import SyntheticThirdPartyTester
import logging


if '__main__' == __name__:
    logger = logging.getLogger(__name__)
    logging.basicConfig(
        format="%(asctime)s %(levelname)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        level=logging.INFO
    )

    synTester = SyntheticThirdPartyTester()
    synTester.run()
